name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Train model
      run: |
        python train.py
    - name: Run tests
      run: |
        pytest tests/
    - name: Upload model artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: best-model
        path: best_model.pth
