name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Train model
      run: |
        python train.py
    - name: Run tests
      run: |
        pytest tests/
    - name: Commit and push model
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add best_model.pth
        git commit -m "Add trained model"
        git push
